name: Transform Tokens

on:
  push:
    paths:
      - 'shared/design-tokens/src/data.json'
    branches:
      - design-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./shared/design-tokens
        run: npm i

      - name: Transform & Build Tokens
        working-directory: ./shared/design-tokens
        run: npm run build:tokens

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          commit-message: 'design(root): update design tokens from figma'
          title: 'ğŸ¤– Design Tokens Update'
          body: |
            Figma Tokens Studioì—ì„œ ìƒˆë¡œìš´ ë””ìì¸ í† í°ì´ ì—…ë°ì´íŠ¸ë˜ì—ˆìŠµë‹ˆë‹¤.
            ìë™ ë³€í™˜ëœ ìŠ¤íƒ€ì¼ íŒŒì¼ì„ í™•ì¸í•´ì£¼ì„¸ìš”.
          branch: 'design-tokens-update'
          delete-branch: true
          base: design-tokens
